mytestkey=This value is from LOCAL properties file

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PayPal Provider Service
paypalprovider.create.order.url=http://localhost:8083/payments